package com.textme.connection;

public enum PackageType {
    GET_USER_DIALOGUES,
    GET_NEW_MESSAGE,
    SEND_USER_DIALOGUES,
    SEND_USER_MESSAGES,
    SEND_USER_MESSAGES_END,
    SEND_USER_DIALOGUES_END,
    SEND_TEXT_MESSAGE,
    GET_USERS_MESSAGES,
    USER_NAME,
    USER_REGISTRATION,
    USER_AUTHORIZATION,
    USER_REGISTERED_SUCCESSFULLY,
    USER_REGISTERED_ERROR,
    USER_LOGIN,
    USER_LOGIN_SUCCESSFULLY,
    USER_LOGIN_ERROR,
    USER_LOG_OUT
}
