package com.textme.connection;

public enum PackageType {
    GET_USER_DIALOGUES,
    SEND_USER_DIALOGUES,
    UPDATING_MESSAGES,
    SEND_TEXT_MESSAGE,
    INCOME_MESSAGE,
    GET_USERS_MESSAGES,
    USER_REGISTRATION,
    USER_REGISTERED_SUCCESSFULLY,
    USER_REGISTERED_ERROR,
    USER_LOGIN,
    USER_LOGIN_SUCCESSFULLY,
    USER_LOGIN_ERROR,
    USER_LOG_OUT
}
