package com.textme.connection;

public enum PackageType {
    SEND_TEXT_MESSAGE,
    GET_USER_MESSAGES,
    USER_NAME,
    USER_REGISTRATION,
    USER_AUTHORIZATION,
    USER_REGISTERED_SUCCESSFULLY,
    USER_REGISTERED_ERROR,
    USER_LOGIN,
    USER_LOGIN_SUCCESSFULLY,
    USER_LOGIN_ERROR,
    USER_LOG_OUT
}
